from dataclasses import dataclass, field
from typing import List, Optional

import pandas as pd
from PyQt6.QtCore import QTimer, Qt
from PyQt6.QtGui import QFont
from PyQt6.QtWidgets import QAbstractItemView, QButtonGroup, QCheckBox, QComboBox, QDialog, QFrame, QGroupBox, \
    QHBoxLayout, QLabel, QLineEdit, QListWidget, QListWidgetItem, QPushButton, QRadioButton, QVBoxLayout, QWidget

from icons import IconBuilder, IconType
from src.core.data_handler import DataHandler
from src.core.global_signals import LogLevel, ToastLevel, global_signals

@dataclass
class ExportConfig:
    """Configuration object generated by ExportDialog"""
    format: str
    include_index: bool
    to_clipboard: bool
    selected_rows_only: bool
    specific_columns: bool
    selected_columns: List[str] = field(default_factory=list)

class ExportDialog(QDialog):
    """Dialog for exporting data"""

    EXPORT_CONFIG: dict[str, dict[str, str]] = {
        "CSV"     : {
            "desc"  : "Standard Comma Separated Values file.",
            "filter": "CSV Files (*.csv)",
            "ext"   : ".csv",
            "method": "to_csv"
        },
        "TSV"     : {
            "desc"  : "Tab Separated Values file.",
            "filter": "TSV Files (*.tsv)",
            "ext"   : ".tsv",
            "method": "to_csv",
            "kwargs": {"sep": "\t"}
        },
        "XLSX"    : {
            "desc"  : "Microsoft Excel Spreadsheet format.",
            "filter": "Excel Files (*.xlsx)",
            "ext"   : ".xlsx",
            "method": "to_excel"
        },
        "JSON"    : {
            "desc"  : "",
            "filter": "JSON Files (*.json)",
            "ext"   : ".json",
            "method": "to_json",
            "kwargs": {"indent": 4}
        },
        "HTML"    : {
            "desc"  : "Export as a static HTML table.",
            "filter": "HTML Files (*.html)",
            "ext"   : ".html",
            "method": "to_html"
        },
        "Markdown": {
            "desc"     : "Export as a Markdown formatted table (requires 'tabulate').",
            "filter"   : "Markdown Files (*.md)",
            "ext"      : ".md",
            "method"   : "to_markdown",
            "error_msg": "Exporting to Markdown requires the 'tabulate' library. Please install it."
        },
        "XML"     : {
            "desc"     : "Export as an Extensible Markup Language file.",
            "filter"   : "XML Files (*.xml)",
            "ext"      : ".xml",
            "method"   : "to_xml",
            "error_msg": "Exporting to XML requires the 'lxml' library. Please install it."
        },
        "Parquet" : {
            "desc"     : "Apache Parquet columnar storage format (requires 'pyarrow').",
            "filter"   : "Parquet Files (*.parquet)",
            "ext"      : ".parquet",
            "method"   : "to_parquet",
            "error_msg": "Exporting to Parquet requires the 'pyarrow' or 'fastparquet' library. Please install one of them."
        }
    }

    def __init__(self, parent: Optional[QWidget] = None, data_handler: Optional[DataHandler] = None,
                 selected_rows: Optional[List[int]] = None, selected_columns: Optional[List[str]] = None):
        super().__init__(parent)
        self.setWindowTitle("Export Data to file")
        self.setWindowIcon(IconBuilder.build(IconType.ExportFle))
        self.setModal(True)
        self.resize(700, 600)

        self.data_handler: DataHandler = data_handler
        self.selected_rows: List[int] = selected_rows if selected_rows is not None else []
        self.pre_selected_columns: List[str] = selected_columns if selected_columns is not None else []

        self.has_row_selection: bool = len(self.selected_rows) > 0
        self.has_col_selection: bool = len(self.pre_selected_columns) > 0

        self.to_clipboard: bool = False
        self.filepath: Optional[str] = None

        self.available_columns = []
        if self.data_handler and self.data_handler.df is not None:
            self.available_columns = list(self.data_handler.df.columns)

        self.init_ui()

    def init_ui(self):
        """Initialize dialog UI"""
        layout = QVBoxLayout(self)
        layout.setContentsMargins(20, 20, 20, 20)
        layout.setSpacing(15)

        # Format selection
        format_layout = QHBoxLayout()
        format_label = QLabel("&Export Format:")
        format_label.setFont(QFont("Consolas", 11, QFont.Weight.Bold))
        format_layout.addWidget(format_label)

        self.format_combo = QComboBox()
        self.format_combo.addItems(["CSV", "TSV", "XLSX", "JSON", "HTML", "Markdown", "XML", "Parquet"])
        self.format_combo.setMinimumWidth(150)
        format_label.setBuddy(self.format_combo)
        format_layout.addWidget(self.format_combo)
        format_layout.addStretch()
        layout.addLayout(format_layout)

        # Data selection layout
        selection_group = QGroupBox("Data Selection", parent=self)
        selection_layout = QVBoxLayout()
        selection_layout.setContentsMargins(15, 20, 15, 15)
        selection_layout.setSpacing(12)

        rows_label = QLabel("Rows:")
        rows_label.setFont(QFont("Consolas", 10, QFont.Weight.Bold))
        selection_layout.addWidget(rows_label)

        rows_radio_layout = QHBoxLayout()
        self.rows_group = QButtonGroup(self)

        self.rows_radio_all = QRadioButton("All Rows")
        self.rows_radio_all.setChecked(True)
        self.rows_group.addButton(self.rows_radio_all)
        rows_radio_layout.addWidget(self.rows_radio_all)

        self.rows_radio_selected = QRadioButton(f"Selected Rows Only: {len(self.selected_rows)}")
        self.rows_group.addButton(self.rows_radio_selected)
        rows_radio_layout.addWidget(self.rows_radio_selected)
        rows_radio_layout.addStretch()

        if self.has_row_selection:
            self.rows_radio_selected.setChecked(True)
        else:
            self.rows_radio_all.setChecked(True)
            self.rows_radio_selected.setEnabled(False)
            self.rows_radio_selected.setToolTip("No rows selected in the table")

        selection_layout.addLayout(rows_radio_layout)

        inner_separator = QFrame()
        inner_separator.setFrameShape(QFrame.Shape.HLine)
        inner_separator.setFrameShadow(QFrame.Shadow.Sunken)
        inner_separator.setProperty("styleClass", "dialog_separator")
        selection_layout.addWidget(inner_separator)

        cols_label = QLabel("Columns:")
        cols_label.setFont(QFont("Consolas", 10, QFont.Weight.Bold))
        selection_layout.addWidget(cols_label)

        cols_radio_layout = QHBoxLayout()
        self.cols_group = QButtonGroup(self)

        self.cols_radio_all = QRadioButton("All Columns")
        self.cols_radio_all.setChecked(True)
        self.cols_group.addButton(self.cols_radio_all)
        cols_radio_layout.addWidget(self.cols_radio_all)

        self.cols_radio_specific = QRadioButton("Specific Columns")
        self.cols_group.addButton(self.cols_radio_specific)
        cols_radio_layout.addWidget(self.cols_radio_specific)
        cols_radio_layout.addStretch()
        selection_layout.addLayout(cols_radio_layout)

        self.column_tools_widget = QWidget()
        column_tools_layout = QVBoxLayout(self.column_tools_widget)
        column_tools_layout.setContentsMargins(0, 5, 0, 0)
        column_tools_layout.setSpacing(8)

        tools_row_layout = QHBoxLayout()
        self.column_filter_input = QLineEdit()
        self.column_filter_input.setPlaceholderText("Filter columns...")
        self.column_filter_input.setClearButtonEnabled(True)

        self.filter_timer = QTimer(self)
        self.filter_timer.setSingleShot(True)
        self.filter_timer.setInterval(250)
        self.filter_timer.timeout.connect(self._filter_columns)

        self.column_filter_input.textChanged.connect(self._apply_column_filter)
        tools_row_layout.addWidget(self.column_filter_input, stretch=1)

        self.select_alL_button = QPushButton("Select all", parent=self)
        self.select_alL_button.clicked.connect(self._select_all_columns)
        tools_row_layout.addWidget(self.select_alL_button)

        self.clear_selection_button = QPushButton("Clear", parent=self)
        self.clear_selection_button.clicked.connect(self._clear_column_selection)
        tools_row_layout.addWidget(self.clear_selection_button)

        column_tools_layout.addLayout(tools_row_layout)

        self.column_list = QListWidget()
        self.column_list.setSelectionMode(QAbstractItemView.SelectionMode.MultiSelection)
        column_tools_layout.addWidget(self.column_list)

        selection_layout.addWidget(self.column_tools_widget)

        if self.available_columns:
            for col in self.available_columns:
                item = QListWidgetItem(col)
                item.setFlags(item.flags() | Qt.ItemFlag.ItemIsUserCheckable)

                if self.has_col_selection and col in self.pre_selected_columns:
                    item.setCheckState(Qt.CheckState.Checked)
                elif not self.has_col_selection:
                    item.setCheckState(Qt.CheckState.Checked)
                else:
                    item.setCheckState(Qt.CheckState.Unchecked)
                self.column_list.addItem(item)
        else:
            empty_item = QListWidgetItem("No Columns Available")
            empty_item.setFlags(Qt.ItemFlag.NoItemFlags)
            empty_item.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.column_list.addItem(empty_item)
            self.column_tools_widget.setEnabled(False)
            self.cols_radio_specific.setEnabled(False)

        if self.has_col_selection and len(self.pre_selected_columns) < len(self.available_columns):
            self.cols_radio_specific.setChecked(True)
            self.column_tools_widget.setEnabled(True)
        else:
            self.cols_radio_all.setChecked(True)
            self.column_tools_widget.setEnabled(False)

        self.cols_radio_all.toggled.connect(self.toggle_column_list)
        self.cols_radio_specific.toggled.connect(self.toggle_column_list)

        selection_group.setLayout(selection_layout)
        layout.addWidget(selection_group)

        options_group = QGroupBox("Options", parent=self)
        options_layout = QVBoxLayout()
        options_layout.setContentsMargins(15, 20, 15, 15)
        options_layout.setSpacing(8)

        self.include_index_check = QCheckBox("Include Index")
        self.include_index_check.setChecked(False)
        options_layout.addWidget(self.include_index_check)

        self.description_label = QLabel()
        self.description_label.setProperty("styleClass", "muted_text")
        self.description_label.setWordWrap(True)
        self.description_label.setMinimumHeight(40)
        options_layout.addWidget(self.description_label)

        options_group.setLayout(options_layout)
        layout.addWidget(options_group)

        layout.addStretch()

        footer_layout = QVBoxLayout()
        footer_layout.setSpacing(10)

        self.summary_label = QLabel("Calculating Summary...")
        self.summary_label.setProperty("styleClass", "muted_text")
        self.summary_label.setAlignment(Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignVCenter)
        footer_layout.addWidget(self.summary_label)

        separator = QFrame()
        separator.setFrameShape(QFrame.Shape.HLine)
        separator.setFrameShadow(QFrame.Shadow.Sunken)
        separator.setProperty("styleClass", "dialog_separator")
        footer_layout.addWidget(separator)

        button_layout = QHBoxLayout()

        self.clipboard_button = QPushButton("Copy to clipboard", parent=self)
        self.clipboard_button.setIcon(IconBuilder.build(IconType.Copy))
        self.clipboard_button.setToolTip("Copy the data to system clipboard")
        self.clipboard_button.clicked.connect(self.on_clipboard_clicked)
        button_layout.addWidget(self.clipboard_button)

        self.export_button = QPushButton("Export")
        self.export_button.setObjectName("MainActionButton")
        self.export_button.setIcon(IconBuilder.build(IconType.ExportFle))
        self.export_button.setMinimumWidth(100)
        self.export_button.setDefault(True)
        self.export_button.clicked.connect(self.on_export_clicked)
        button_layout.addWidget(self.export_button)

        self.cancel_button = QPushButton("Cancel", parent=self)
        self.cancel_button.setMinimumWidth(100)
        self.cancel_button.clicked.connect(self.reject)
        button_layout.addWidget(self.cancel_button)

        footer_layout.addLayout(button_layout)
        layout.addLayout(footer_layout)

        self.setLayout(layout)

        self.column_list.itemChanged.connect(self._validate_selection)
        self.cols_radio_all.toggled.connect(self._validate_selection)
        self.cols_radio_specific.toggled.connect(self._validate_selection)
        self.rows_radio_all.toggled.connect(self._validate_selection)
        self.rows_radio_selected.toggled.connect(self._validate_selection)
        self.format_combo.currentTextChanged.connect(self.update_format_info)
        self.include_index_check.stateChanged.connect(self.update_format_info)
        self.update_format_info()

        self._validate_selection()

    def toggle_column_list(self) -> None:
        """toggle the column list"""
        is_specific = self.cols_radio_specific.isChecked()
        self.column_tools_widget.setEnabled(is_specific)
        if is_specific:
            self.column_filter_input.setFocus()

    def _filter_columns(self) -> None:
        self.filter_timer.start()

    def _apply_column_filter(self) -> None:
        """
        Hide or show columns in the list based on search text
        """
        search_text = self.column_filter_input.text().lower()
        self.column_list.blockSignals(True)
        for index in range(self.column_list.count()):
            item = self.column_list.item(index)
            if item:
                item_text = item.text().lower()
                item.setHidden(search_text not in item_text)
        self.column_list.blockSignals(False)

    def _select_all_columns(self) -> None:
        self.column_list.blockSignals(True)
        for index in range(self.column_list.count()):
            item = self.column_list.item(index)
            if item and not item.isHidden():
                item.setCheckState(Qt.CheckState.Checked)
        self.column_list.blockSignals(False)
        self._validate_selection()

    def _clear_column_selection(self) -> None:
        self.column_list.blockSignals(True)
        for index in range(self.column_list.count()):
            item = self.column_list.item(index)
            if item and not item.isHidden():
                item.setCheckState(Qt.CheckState.Unchecked)
        self.column_list.blockSignals(False)
        self._validate_selection()

    def _get_checked_columns(self) -> List[str]:
        """Return a list of column names that are currently checked"""
        return [
            self.column_list.item(i).text() for i in range(self.column_list.count()) if
            self.column_list.item(i).checkState() == Qt.CheckState.Checked
        ]

    def _get_checked_columns_count(self) -> int:
        """Return the total number of check columns"""
        return sum(
            1 for i in range(self.column_list.count()) if self.column_list.item(i).checkState() == Qt.CheckState.Checked
        )

    def _validate_selection(self) -> None:
        is_valid: bool = True
        if self.cols_radio_specific.isChecked():
            if self._get_checked_columns_count() == 0:
                is_valid = False

        self.export_button.setEnabled(is_valid)
        self.clipboard_button.setEnabled(is_valid)

        self._update_summary()

    def _update_summary(self) -> None:
        if not self.data_handler or self.data_handler.df is None:
            self.summary_label.setText("0 rows x 0 columns")
            return

        if self.rows_radio_selected.isChecked() and self.has_row_selection:
            rows = len(self.selected_rows)
        else:
            rows = len(self.data_handler.df)

        if self.cols_radio_specific.isChecked():
            cols = self._get_checked_columns_count()
        else:
            cols = len(self.available_columns)

        self.summary_label.setText(f"<b>Summary:</b> {rows:,} rows x {cols:,} columns")

    def update_format_info(self) -> None:
        """Update a description label based on selected format and current optins"""
        format_selection = self.format_combo.currentText()
        include_index = self.include_index_check.isChecked()

        self.export_button.setText(f"Export to {format_selection}...")

        if format_selection == "JSON":
            orient = "columns" if include_index else "records"
            self.description_label.setText(f"Export as a '{orient}' oriented JSON")
        else:
            config = self.EXPORT_CONFIG.get(format_selection, {})
            self.description_label.setText(config.get("desc", ""))

    def on_clipboard_clicked(self) -> None:
        """Triggered when copy to clipboard is clicked"""
        self.to_clipboard = True
        self.accept()

    def on_export_clicked(self) -> None:
        """Triggered when standard export is clicked"""
        self.to_clipboard = False
        self.accept()

    def _get_export_data(self) -> Optional[pd.DataFrame]:
        """Get the dataframe current selection"""
        if not self.data_handler or self.data_handler.df is None:
            return None

        df = self.data_handler.df

        if self.rows_radio_selected.isChecked() and self.selected_rows:
            try:
                df = df.iloc[self.selected_rows]
            except IndexError as error:
                global_signals.request_toast(
                    "Selection Error", "Error slicing selected rows. They may be out of bounds", ToastLevel.ERROR
                )
                global_signals.request_log(
                    f"Error slicing selected rows. They may be out of bounds: {str(error)}", LogLevel.ERROR
                )
                return None
            except Exception as error:
                global_signals.request_toast(
                    "Slicing Error", "An unexpected error occurred while filtering rows", ToastLevel.ERROR
                )
                global_signals.request_log(
                    f"An unexpected error occurred while filtering rows: {str(error)}", LogLevel.ERROR
                )
                return None

        if self.cols_radio_specific.isChecked():
            selected_cols = self._get_checked_columns()
            if not selected_cols:
                global_signals.request_toast(
                    "No Columns Selected", "Please select at least one column to export", ToastLevel.WARNING
                )
                return None
            df = df[selected_cols]
        return df

    def get_export_config(self) -> ExportConfig:
        """Return export configuration object"""
        return ExportConfig(
            format=self.format_combo.currentText(),
            include_index=self.include_index_check.isChecked(),
            to_clipboard=self.to_clipboard,
            selected_rows_only=self.rows_radio_selected.isChecked(),
            specific_columns=self.cols_radio_specific.isChecked(),
            selected_columns=self._get_checked_columns()
        )
